name: Notify Telegram on PR Merge to Master

on:
  pull_request:
    types: [closed]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Get Commit Author Info
        id: commit_author
        run: |
          COMMIT_SHA="${{ github.event.pull_request.head.sha }}"
          AUTHOR_NAME=$(git log -1 --pretty=format:'%an' ${COMMIT_SHA})
          AUTHOR_EMAIL=$(git log -1 --pretty=format:'%ae' ${COMMIT_SHA})
          echo "AUTHOR_NAME=${AUTHOR_NAME}" >> $GITHUB_ENV
          echo "AUTHOR_EMAIL=${AUTHOR_EMAIL}" >> $GITHUB_ENV

      - name: Send Direct Telegram Notification
        if: ${{ github.event.pull_request.merged }}
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_DIRECT_CHAT_ID }}
          LOCATION: ${{ secrets.CURRENT_LOCATION }}
        run: |
          AUTHOR_NICKNAME="${{ github.event.pull_request.user.login }}"
          AUTHOR_NAME="${{ env.AUTHOR_NAME }}"
          AUTHOR_EMAIL="${{ env.AUTHOR_EMAIL }}"
          COMMIT_MESSAGE="${{ github.event.pull_request.title }}"
          REPO_NAME="${{ github.repository }}"
          PR_NUMBER="${{ github.event.pull_request.number }}"
          PR_URL="https://github.com/${{ github.repository }}/pull/${PR_NUMBER}"

          MESSAGE="A pull request ${PR_URL}
          has been merged into master in ${REPO_NAME}.

          Commit: ${COMMIT_MESSAGE}
          Author: ${AUTHOR_NAME} @ ${AUTHOR_NICKNAME}
          Location: ${LOCATION}"

          curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage" \
            -d chat_id="${TELEGRAM_CHAT_ID}" \
            -d text="${MESSAGE}"

      - name: Send Chat Telegram Notification
        if: ${{ github.event.pull_request.merged }}
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_2R_CHAT_ID }}
          LOCATION: ${{ secrets.CURRENT_LOCATION }}
        run: |
          AUTHOR_NICKNAME="${{ github.event.pull_request.user.login }}"
          AUTHOR_NAME="${{ env.AUTHOR_NAME }}"
          AUTHOR_EMAIL="${{ env.AUTHOR_EMAIL }}"
          COMMIT_MESSAGE="${{ github.event.pull_request.title }}"
          REPO_NAME="${{ github.repository }}"
          PR_NUMBER="${{ github.event.pull_request.number }}"
          PR_URL="https://github.com/${{ github.repository }}/pull/${PR_NUMBER}"

          MESSAGE="A pull request ${PR_URL}
          has been merged into master in ${REPO_NAME}.

          Commit: ${COMMIT_MESSAGE}
          Author: ${AUTHOR_NAME} @ ${AUTHOR_NICKNAME}
          Location: ${LOCATION}"

          curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage" \
            -d chat_id="${TELEGRAM_CHAT_ID}" \
            -d text="${MESSAGE}"

