name: Notify Telegram on PR Merge to Master

on:
  pull_request:
    types: [closed]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Send Direct Telegram Notification
        if: ${{ github.event.pull_request.merged }}
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_DIRECT_CHAT_ID }}
          LOCATION: ${{ secrets.CURRENT_LOCATION }}
        run: |
          declare -A USER_MAP
          USER_MAP["FLlGHT"]="Michael Fedorenko (@FLlGHT)"
          USER_MAP["APFan"]="Mikhail Osokin (@maosokin)"
          USER_MAP["addicted-by"]="Aleksei Riabykin (@addicted_by)"

          AUTHOR_NICKNAME="${{ github.event.pull_request.user.login }}"
          TELEGRAM_USERNAME=${USER_MAP[$AUTHOR_NICKNAME]}
          COMMIT_MESSAGE="${{ github.event.pull_request.title }}"
          REPO_NAME="${{ github.repository }}"
          PR_NUMBER="${{ github.event.pull_request.number }}"
          PR_URL="https://github.com/${{ github.repository }}/pull/${PR_NUMBER}"
          ADDITIONS="${{ github.event.pull_request.additions }}"
          DELETIONS="${{ github.event.pull_request.deletions }}"
          CHANGED_FILES="${{ github.event.pull_request.changed_files }}"
          SHA="${{ github.event.pull_request.merge_commit_sha }}"

          MESSAGE="A pull request ${PR_URL}
          has been merged into master in ${REPO_NAME}.

          Commit: ${COMMIT_MESSAGE}
          Author: ${TELEGRAM_USERNAME}
          Location: ${LOCATION}
          Changed files: ${CHANGED_FILES} (%2B ${ADDITIONS} - ${DELETIONS})
          Commit sha: ${SHA}
          "

          curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage" \
            -d chat_id="${TELEGRAM_CHAT_ID}" \
            -d text="${MESSAGE}"

      - name: Send Chat Telegram Notification
        if: ${{ github.event.pull_request.merged }}
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_2R_CHAT_ID }}
          LOCATION: ${{ secrets.CURRENT_LOCATION }}
        run: |
          declare -A USER_MAP
          USER_MAP["FLlGHT"]="Michael Fedorenko (@FLlGHT)"
          USER_MAP["APFan"]="Mikhail Osokin (@maosokin)"
          USER_MAP["addicted-by"]="Aleksei Riabykin (@addicted_by)"

          AUTHOR_NICKNAME="${{ github.event.pull_request.user.login }}"
          TELEGRAM_USERNAME=${USER_MAP[$AUTHOR_NICKNAME]}
          COMMIT_MESSAGE="${{ github.event.pull_request.title }}"
          REPO_NAME="${{ github.repository }}"
          PR_NUMBER="${{ github.event.pull_request.number }}"
          PR_URL="https://github.com/${{ github.repository }}/pull/${PR_NUMBER}"

          ADDITIONS="${{ github.event.pull_request.additions }}"
          DELETIONS="${{ github.event.pull_request.deletions }}"
          CHANGED_FILES="${{ github.event.pull_request.changed_files }}"
          SHA="${{ github.event.pull_request.merge_commit_sha }}"

          MESSAGE="A pull request ${PR_URL}
          has been merged into master in ${REPO_NAME}.

          Commit: ${COMMIT_MESSAGE}
          Author: ${TELEGRAM_USERNAME}
          Location: ${LOCATION}
          Changed files: ${CHANGED_FILES} (%2B ${ADDITIONS} - ${DELETIONS})
          Commit sha: ${SHA}
          "

          curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage" \
            -d chat_id="${TELEGRAM_CHAT_ID}" \
            -d text="${MESSAGE}"

